### ISSUE TITLE
Address doesn't match seed?

### ISSUE THREAD

**Issue by Crypto2** [wavesplatform/waves-php#6]
Since the Waves devs purposely crippled their coin I'm trying to get a workaround going since we use PHP. When I try sending Waves I'm getting the address seed from the node with /addresses/seed/<address> but when I plug it in to waves-php the address doesn't match.

$account = PrivateKey::fromString( 'returned base58 seed' );
$sender = $account->publicKey();
echo 'address = ' . $sender->address()->toString() . PHP_EOL;

**Comment by deemru** [comment]
The node returns an account seed in base58 string format.

Docs: [Creating a private key from a seed](https://docs.waves.tech/en/blockchain/waves-protocol/cryptographic-practical-details#creating-a-private-key-from-a-seed)

Fixed code:
```php
use Waves\Account\PrivateKey;
use Waves\Common\Base58String;

$accountSeedBase58 = 'H4do9ZcPUASvtFJHvESapnxfmQ8tjBXMU7NtUARk9Jrf';
$accountSeed = Base58String::fromString( $accountSeedBase58 )->bytes();
$accountPrivateKey = hash( 'sha256', $accountSeed, true );
$account = PrivateKey::fromBytes( $accountPrivateKey );
$sender = $account->publicKey();
echo 'address = ' . $sender->address()->toString() . PHP_EOL;
```

**Comment by Crypto2** [comment]
Thanks, worked perfectly :)
